### ISSUE TITLE
Genre Field Numbers

### ISSUE THREAD

**Issue by ktnlikeasmallcat** [Beinsezii/ompl#1]
Hi, do you know what could be causing the Genre field to be populated by genre names as well as numbers - like this?
```
(19)
(43)
(7)
(9)
Breakcore
Digital Hardcore
```
Also, is there a way I haven't noticed that one can set up some kind of .config file for retaining field layouts and library path across reboots and new instances? 
This is so far my CMUS killer. Thank you.

**Comment by Beinsezii** [comment]
'Genre' is set by the `TCON` field on MP3/ID3 and the 'genre' field on flac/ogg.

Run `ompl print track` while a problem file is playing and it'll barf all of its tags into the terminal. That should show what's going on, else just paste the output into a comment so I can see.



Far as the persistent fields/library, on Linux I just created a script called `ompl-default` in `~/.local/bin/` with my args saved:
```bash
#! /usr/bin/env bash

ompl main ~/Music/ --volume 0.65 -f genre album artist "<grouping|<grouping> - ><title>" -s album "<grouping|<grouping> - ><title>" artist
```
And on windows I did the same with a modified Windows Terminal shortcut in my start menu.

There's no automatic config generation as of yet. Feel free to open a separate issue for it if you wish.

**Comment by ktnlikeasmallcat** [comment]
Thank you!
```
/home/ktn/Music/The_Suburbanists/The Suburbanists - Drag It Through The Garden/The Suburbanists - Drag It Through The Garden - 02 Wait Around.mp3
TYER/Year: 2016
TPE1/Artist: The Suburbanists
TPE2/Accompaniment: The Suburbanists
TCON/Genre: (43)
TIT2/Title: Wait Around
TRCK/Track: 02
TALB/Album: Drag It Through The Garden
```
```
/home/ktn/Music/HYPE_MACHINE/BBYmutha - rainyday.mp3
TCON/Genre: (7)
TIT2/Title: rainyday:)
TPE1/Artist: BbyMutha
TPE2/Accompaniment: Various artists
TALB/Album: Hype Machine
TYER/Year: 2021
```

...as opposed to what I'd see in clementine or easytag where the Genre ID3 tag is filled out as expected.

All I looked at a dozen or so, and all the affected tracks are .mp3 files, though there are many .mp3 files that are not affected. Each number also appears to be associated with one genre:(19) is Industrial and (9) is Metal, however, all these tags appear as expected in the <genre> field, for files that are also .mp3's.

**Comment by Beinsezii** [comment]
Hm. Wonder if there's some predefined list of genres that the numbers are supposed to be interpreted as.

Does it still output (N) when you dump all the meta using something like `ffmpeg`?

**Comment by Beinsezii** [comment]
yup.

https://id3.org/id3v2.3.0#Appendix_A_-_Genre_List_from_ID3v1

Should be doable in a few minutes tomorrow.
